version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: media_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/media_api
      PYTHONPATH: /app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/.venv  # Prevent poetry venv from being overridden
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: